// Mocks generated by Mockito 5.4.6 from annotations
// in stash_app_flutter/test/features/scenes/presentation/providers/playend_behavior_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i19;
import 'dart:ui' as _i22;

import 'package:flutter/widgets.dart' as _i7;
import 'package:media_kit/media_kit.dart' as _i5;
import 'package:media_kit/src/models/audio_device.dart' as _i17;
import 'package:media_kit/src/models/media/media.dart' as _i15;
import 'package:media_kit/src/models/playable.dart' as _i14;
import 'package:media_kit/src/models/player_state.dart' as _i3;
import 'package:media_kit/src/models/player_stream.dart' as _i4;
import 'package:media_kit/src/models/playlist_mode.dart' as _i16;
import 'package:media_kit/src/models/track.dart' as _i18;
import 'package:media_kit/src/player/platform_player.dart' as _i13;
import 'package:media_kit_video/src/video_controller/platform_video_controller.dart'
    as _i21;
import 'package:media_kit_video/src/video_controller/video_controller.dart'
    as _i20;
import 'package:mockito/mockito.dart' as _i1;
import 'package:stash_app_flutter/core/domain/entities/scraped/scraped_scene.dart'
    as _i11;
import 'package:stash_app_flutter/features/scenes/data/repositories/graphql_scene_repository.dart'
    as _i8;
import 'package:stash_app_flutter/features/scenes/domain/entities/scene.dart'
    as _i2;
import 'package:stash_app_flutter/features/scenes/domain/entities/scene_deduplication.dart'
    as _i12;
import 'package:stash_app_flutter/features/scenes/domain/entities/scene_filter.dart'
    as _i9;
import 'package:stash_app_flutter/features/scenes/domain/models/scraper.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeScene_0 extends _i1.SmartFake implements _i2.Scene {
  _FakeScene_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSceneMarker_1 extends _i1.SmartFake implements _i2.SceneMarker {
  _FakeSceneMarker_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlayerState_2 extends _i1.SmartFake implements _i3.PlayerState {
  _FakePlayerState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlayerStream_3 extends _i1.SmartFake implements _i4.PlayerStream {
  _FakePlayerStream_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlayer_4 extends _i1.SmartFake implements _i5.Player {
  _FakePlayer_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCompleter_5<T> extends _i1.SmartFake implements _i6.Completer<T> {
  _FakeCompleter_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueNotifier_6<T> extends _i1.SmartFake
    implements _i7.ValueNotifier<T> {
  _FakeValueNotifier_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GraphQLSceneRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphQLSceneRepository extends _i1.Mock
    implements _i8.GraphQLSceneRepository {
  MockGraphQLSceneRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.Scene>> findScenes({
    int? page,
    int? perPage,
    String? filter,
    String? sort,
    bool? descending = true,
    bool? organized,
    bool? performerFavorite,
    String? performerId,
    String? studioId,
    String? tagId,
    _i9.SceneFilter? sceneFilter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findScenes, [], {
              #page: page,
              #perPage: perPage,
              #filter: filter,
              #sort: sort,
              #descending: descending,
              #organized: organized,
              #performerFavorite: performerFavorite,
              #performerId: performerId,
              #studioId: studioId,
              #tagId: tagId,
              #sceneFilter: sceneFilter,
            }),
            returnValue: _i6.Future<List<_i2.Scene>>.value(<_i2.Scene>[]),
          )
          as _i6.Future<List<_i2.Scene>>);

  @override
  _i6.Future<_i2.Scene> getSceneById(String? id, {bool? refresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getSceneById, [id], {#refresh: refresh}),
            returnValue: _i6.Future<_i2.Scene>.value(
              _FakeScene_0(
                this,
                Invocation.method(#getSceneById, [id], {#refresh: refresh}),
              ),
            ),
          )
          as _i6.Future<_i2.Scene>);

  @override
  _i6.Future<_i2.SceneMarker> createSceneMarker({
    required String? sceneId,
    required String? title,
    double? seconds = 0.0,
    double? endSeconds,
    String? primaryTagId,
    List<String>? tagIds = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSceneMarker, [], {
              #sceneId: sceneId,
              #title: title,
              #seconds: seconds,
              #endSeconds: endSeconds,
              #primaryTagId: primaryTagId,
              #tagIds: tagIds,
            }),
            returnValue: _i6.Future<_i2.SceneMarker>.value(
              _FakeSceneMarker_1(
                this,
                Invocation.method(#createSceneMarker, [], {
                  #sceneId: sceneId,
                  #title: title,
                  #seconds: seconds,
                  #endSeconds: endSeconds,
                  #primaryTagId: primaryTagId,
                  #tagIds: tagIds,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.SceneMarker>);

  @override
  _i6.Future<void> deleteSceneMarker(String? markerId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSceneMarker, [markerId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i10.Scraper>> listScrapers({required List<String>? types}) =>
      (super.noSuchMethod(
            Invocation.method(#listScrapers, [], {#types: types}),
            returnValue: _i6.Future<List<_i10.Scraper>>.value(<_i10.Scraper>[]),
          )
          as _i6.Future<List<_i10.Scraper>>);

  @override
  _i6.Future<List<_i11.ScrapedScene>> scrapeSingleScene({
    String? scraperId,
    String? stashBoxEndpoint,
    String? sceneId,
    String? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scrapeSingleScene, [], {
              #scraperId: scraperId,
              #stashBoxEndpoint: stashBoxEndpoint,
              #sceneId: sceneId,
              #query: query,
            }),
            returnValue: _i6.Future<List<_i11.ScrapedScene>>.value(
              <_i11.ScrapedScene>[],
            ),
          )
          as _i6.Future<List<_i11.ScrapedScene>>);

  @override
  _i6.Future<_i11.ScrapedScene?> scrapeSceneURL(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#scrapeSceneURL, [url]),
            returnValue: _i6.Future<_i11.ScrapedScene?>.value(),
          )
          as _i6.Future<_i11.ScrapedScene?>);

  @override
  _i6.Future<void> generatePhash(String? sceneId) =>
      (super.noSuchMethod(
            Invocation.method(#generatePhash, [sceneId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveScrapedScene({
    required String? sceneId,
    required _i11.ScrapedScene? scraped,
    bool? mergeValues = false,
    List<String>? performerIds,
    List<String>? tagIds,
    String? studioId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveScrapedScene, [], {
              #sceneId: sceneId,
              #scraped: scraped,
              #mergeValues: mergeValues,
              #performerIds: performerIds,
              #tagIds: tagIds,
              #studioId: studioId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, List<Map<String, dynamic>>>> findPerformerCandidates(
    List<String>? performers,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findPerformerCandidates, [performers]),
            returnValue:
                _i6.Future<Map<String, List<Map<String, dynamic>>>>.value(
                  <String, List<Map<String, dynamic>>>{},
                ),
          )
          as _i6.Future<Map<String, List<Map<String, dynamic>>>>);

  @override
  _i6.Future<Map<String, List<Map<String, dynamic>>>> findTagCandidates(
    List<String>? tags,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findTagCandidates, [tags]),
            returnValue:
                _i6.Future<Map<String, List<Map<String, dynamic>>>>.value(
                  <String, List<Map<String, dynamic>>>{},
                ),
          )
          as _i6.Future<Map<String, List<Map<String, dynamic>>>>);

  @override
  _i6.Future<void> updateSceneRating(String? id, int? rating100) =>
      (super.noSuchMethod(
            Invocation.method(#updateSceneRating, [id, rating100]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> incrementSceneOCounter(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#incrementSceneOCounter, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> incrementScenePlayCount(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#incrementScenePlayCount, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveSceneActivity(
    String? id, {
    double? resumeTime,
    double? playDuration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveSceneActivity,
              [id],
              {#resumeTime: resumeTime, #playDuration: playDuration},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteScene(
    String? id, {
    required bool? deleteFile,
    bool? deleteGenerated = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteScene,
              [id],
              {#deleteFile: deleteFile, #deleteGenerated: deleteGenerated},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i12.SceneDuplicateGroup>> findDuplicateScenes({
    int? distance = 0,
    double? durationDiff = 1.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findDuplicateScenes, [], {
              #distance: distance,
              #durationDiff: durationDiff,
            }),
            returnValue: _i6.Future<List<_i12.SceneDuplicateGroup>>.value(
              <_i12.SceneDuplicateGroup>[],
            ),
          )
          as _i6.Future<List<_i12.SceneDuplicateGroup>>);

  @override
  _i6.Future<int> countScenesMissingPhash() =>
      (super.noSuchMethod(
            Invocation.method(#countScenesMissingPhash, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);
}

/// A class which mocks [Player].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayer extends _i1.Mock implements _i5.Player {
  MockPlayer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PlayerState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakePlayerState_2(this, Invocation.getter(#state)),
          )
          as _i3.PlayerState);

  @override
  _i4.PlayerStream get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _FakePlayerStream_3(this, Invocation.getter(#stream)),
          )
          as _i4.PlayerStream);

  @override
  _i4.PlayerStream get streams =>
      (super.noSuchMethod(
            Invocation.getter(#streams),
            returnValue: _FakePlayerStream_3(this, Invocation.getter(#streams)),
          )
          as _i4.PlayerStream);

  @override
  _i6.Future<int> get handle =>
      (super.noSuchMethod(
            Invocation.getter(#handle),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  set platform(_i13.PlatformPlayer? value) => super.noSuchMethod(
    Invocation.setter(#platform, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> open(_i14.Playable? playable, {bool? play = true}) =>
      (super.noSuchMethod(
            Invocation.method(#open, [playable], {#play: play}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> play() =>
      (super.noSuchMethod(
            Invocation.method(#play, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> playOrPause() =>
      (super.noSuchMethod(
            Invocation.method(#playOrPause, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> add(_i15.Media? media) =>
      (super.noSuchMethod(
            Invocation.method(#add, [media]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> remove(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [index]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> next() =>
      (super.noSuchMethod(
            Invocation.method(#next, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> previous() =>
      (super.noSuchMethod(
            Invocation.method(#previous, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> jump(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#jump, [index]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> move(int? from, int? to) =>
      (super.noSuchMethod(
            Invocation.method(#move, [from, to]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> seek(Duration? duration) =>
      (super.noSuchMethod(
            Invocation.method(#seek, [duration]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setPlaylistMode(_i16.PlaylistMode? playlistMode) =>
      (super.noSuchMethod(
            Invocation.method(#setPlaylistMode, [playlistMode]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setRate(double? rate) =>
      (super.noSuchMethod(
            Invocation.method(#setRate, [rate]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setPitch(double? pitch) =>
      (super.noSuchMethod(
            Invocation.method(#setPitch, [pitch]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setShuffle(bool? shuffle) =>
      (super.noSuchMethod(
            Invocation.method(#setShuffle, [shuffle]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setAudioDevice(_i17.AudioDevice? audioDevice) =>
      (super.noSuchMethod(
            Invocation.method(#setAudioDevice, [audioDevice]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setVideoTrack(_i18.VideoTrack? track) =>
      (super.noSuchMethod(
            Invocation.method(#setVideoTrack, [track]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setAudioTrack(_i18.AudioTrack? track) =>
      (super.noSuchMethod(
            Invocation.method(#setAudioTrack, [track]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setSubtitleTrack(_i18.SubtitleTrack? track) =>
      (super.noSuchMethod(
            Invocation.method(#setSubtitleTrack, [track]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i19.Uint8List?> screenshot({
    String? format = 'image/jpeg',
    bool? includeLibassSubtitles = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#screenshot, [], {
              #format: format,
              #includeLibassSubtitles: includeLibassSubtitles,
            }),
            returnValue: _i6.Future<_i19.Uint8List?>.value(),
          )
          as _i6.Future<_i19.Uint8List?>);
}

/// A class which mocks [VideoController].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoController extends _i1.Mock implements _i20.VideoController {
  MockVideoController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Player get player =>
      (super.noSuchMethod(
            Invocation.getter(#player),
            returnValue: _FakePlayer_4(this, Invocation.getter(#player)),
          )
          as _i5.Player);

  @override
  _i6.Completer<_i21.PlatformVideoController> get platform =>
      (super.noSuchMethod(
            Invocation.getter(#platform),
            returnValue: _FakeCompleter_5<_i21.PlatformVideoController>(
              this,
              Invocation.getter(#platform),
            ),
          )
          as _i6.Completer<_i21.PlatformVideoController>);

  @override
  _i7.ValueNotifier<_i21.PlatformVideoController?> get notifier =>
      (super.noSuchMethod(
            Invocation.getter(#notifier),
            returnValue: _FakeValueNotifier_6<_i21.PlatformVideoController?>(
              this,
              Invocation.getter(#notifier),
            ),
          )
          as _i7.ValueNotifier<_i21.PlatformVideoController?>);

  @override
  _i7.ValueNotifier<int?> get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _FakeValueNotifier_6<int?>(
              this,
              Invocation.getter(#id),
            ),
          )
          as _i7.ValueNotifier<int?>);

  @override
  _i7.ValueNotifier<_i22.Rect?> get rect =>
      (super.noSuchMethod(
            Invocation.getter(#rect),
            returnValue: _FakeValueNotifier_6<_i22.Rect?>(
              this,
              Invocation.getter(#rect),
            ),
          )
          as _i7.ValueNotifier<_i22.Rect?>);

  @override
  _i6.Future<void> get waitUntilFirstFrameRendered =>
      (super.noSuchMethod(
            Invocation.getter(#waitUntilFirstFrameRendered),
            returnValue: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setSize({int? width, int? height}) =>
      (super.noSuchMethod(
            Invocation.method(#setSize, [], {#width: width, #height: height}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
